name: ABP_Bookstore_Tests

on:
  push:
    branches: ["main", "pre-view-structure"]
  pull_request:
    branches: ["main", "pre-view-structure"]

jobs:
  linuxTests:
    runs-on: ${{matrix.os}}

    defaults:
      run:
        working-directory: ./test/
    
   
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies and build
      run: |
        for proj in $(find . -name '*.csproj'); do
          dotnet restore "$proj" --verbosity normal
          dotnet build "$proj" --no-restore --verbosity normal
        done
      timeout-minutes: 15

    - name: Test
      run: |
        for proj in $(find . -name '*.csproj'); do
          dotnet test "$proj" --no-build --verbosity normal --logger "trx;LogFileName=testresults.trx"
        done
      timeout-minutes: 15

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/TestResults/*.trx'
  

  windowsTests:
    needs: linuxTests  
    runs-on: ${{matrix.os}}

    defaults:
      run:
        working-directory: ./test/
    
   
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies and build
      run: |
        for proj in $(find . -name '*.csproj'); do
            dotnet restore "$proj" --verbosity normal
            dotnet build "$proj" --no-restore --verbosity normal
        done
        timeout-minutes: 15

    - name: Test
      run: |
        for proj in $(find . -name '*.csproj'); do
            dotnet test "$proj" --no-build --verbosity normal --logger "trx;LogFileName=testresults.trx"
        done
        timeout-minutes: 15

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/TestResults/*.trx'